---
layout: page
title: Some errors encountered in the use of pytorch on Cuda
permalink: /share/Experience/231106/
---

<table><tr><td bgcolor=lightgray><strong>Q1: RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1</strong></td></tr></table>

<em>A1: While I tried your code, and it did not give me an error, I can say that usually the best practice to debug CUDA Runtime Errors: device-side assert like yours is to turn collab to CPU and recreate the error. It will give you a more useful traceback error.</em>

<em>Most of the time CUDA Runtime Errors can be the cause of <font color=Blue>some index mismatching</font> so like you tried to train a network with 10 output nodes on a dataset with 15 labels. And the thing with this CUDA error is once you get this error once, you will recieve it for every operation you do with torch.tensors. This forces you to restart your notebook.</em>

<em>I suggest you restart your notebook, get a more accuracate traceback by <font color=Blue>moving to CPU</font>, and check the rest of your code especially if you train a model on set of targets somewhere.</em>

**Q2: csdcds**
